version: "3.7"

services:
  sample-topology:
    image: frinx/sample-topology:td_ptp
    build: .
    environment:
      - DOCKER_GWBRIDGE_IP=localhost
    volumes:
      - ./devices_examples/td_devices_ptp.csv:/sample-topology/devices.csv
    ports:
      - 10000-10100:10000-10100
    command:
      python2.7 main.py
