version: "3.7"

services:
  sample-topology:
    image: frinx/sample-topology
    build: .
    volumes:
      - ./devices.csv:/sample-topology/devices.csv
    ports:
      - 17000-17200:17000-17200
    command:
      python2.7 main.py
